package com.buurman.domain;

import java.time.Instant;
import java.time.LocalDate;
import java.util.Optional;
import java.util.UUID;

import com.buurman.util.MoneyAmount;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@SuppressWarnings("NullAway.Init")
@Data
@Builder(toBuilder = true)
@NoArgsConstructor
@AllArgsConstructor
public class Payment {

  public enum PaymentStatus {
    PENDING,
    PARTIALLY_PAID,
    PAID,
    OVERDUE,
    CANCELLED
  }

  /** What the payment is for: regular rent, or a late fee charged on an overdue rent payment. */
  public enum PaymentType {
    RENT,
    LATE_FEE,
    INSTALMENT
  }

  private UUID id;
  @Builder.Default private Optional<Sid> identifier = Optional.empty();
  private UUID teamId;
  private UUID contractId;
  @Builder.Default private Optional<UUID> contactId = Optional.empty();
  private MoneyAmount amount;
  @Builder.Default private Optional<LocalDate> paymentDate = Optional.empty();
  private LocalDate dueDate;
  private PaymentStatus status;
  @Builder.Default private Optional<String> notes = Optional.empty();
  @Builder.Default private Boolean autoGenerated = false;
  @Builder.Default private PaymentType paymentType = PaymentType.RENT;

  /** For LATE_FEE payments: the rent payment the fee was charged on. */
  @Builder.Default private Optional<UUID> parentPaymentId = Optional.empty();

  @Builder.Default private Optional<String> cancelReason = Optional.empty();
  @Builder.Default private Optional<Instant> waivedAt = Optional.empty();
  @Builder.Default private Optional<UUID> waivedBy = Optional.empty();
  @Builder.Default private Optional<String> waiveReason = Optional.empty();

  /** For INSTALMENT payments: the plan they belong to. */
  @Builder.Default private Optional<UUID> paymentPlanId = Optional.empty();

  private Instant createdAt;
  private Instant updatedAt;
  private UUID createdBy;
  private UUID updatedBy;
  @Builder.Default private Optional<Instant> deletedAt = Optional.empty();
}
