package com.buurman.domain;

public enum TimelineEventType {
  CONTRACT_CREATED,
  CONTRACT_STATUS_CHANGED,
  RENT_CHANGED,
  EXTENSION_CREATED,
  EXTENSION_ACTIVATED,
  EXTENSION_DECLINED,
  DOCUMENT_UPLOADED,
  DOCUMENT_GENERATED,
  SIGNATURE_SENT,
  SIGNATURE_COMPLETED,
  SIGNATURE_DECLINED,
  AUDIT_OTHER
}
