import { createPortal } from 'react-dom';
import { useTranslation } from 'react-i18next';
import { ChevronDown, Languages } from 'lucide-react';
import { Button } from '@buurman/ui';
import { DocumentLanguageList } from './DocumentLanguageList';
import {
  baseLanguage,
  documentLanguageLabel,
  type DocumentLanguageCode,
} from './documentLanguages';
import { useAnchoredPopover } from './useAnchoredPopover';

interface DocumentLanguagePickerProps {
  value: DocumentLanguageCode;
  onChange: (code: DocumentLanguageCode) => void;
  /** Accessible name of the trigger and the popover, e.g. "Agreement language". */
  label: string;
  disabled?: boolean;
}

/**
 * Picks a document language with the booklet menu's language list, for outputs that are
 * generated by a separate action (the lease agreement) instead of on click.
 */
export const DocumentLanguagePicker = ({
  value,
  onChange,
  label,
  disabled = false,
}: DocumentLanguagePickerProps) => {
  const { i18n } = useTranslation('common');
  const { open, setOpen, triggerRef, popoverRef, popoverStyle } = useAnchoredPopover('left');
  const valueLabel = documentLanguageLabel(value);

  const popover =
    open
      ? createPortal(
          <>
            <div
              className="fixed inset-0 z-[9998]"
              onClick={() => setOpen(false)}
              aria-hidden="true"
            />
            <div
              role="menu"
              aria-label={label}
              className="fixed w-72 bg-surface-card rounded-xl shadow-xl border border-border-default z-[9999] flex flex-col overflow-hidden animate-in fade-in zoom-in-95 duration-100"
              ref={popoverRef}
              style={popoverStyle}
            >
              <DocumentLanguageList
                uiLanguage={baseLanguage(i18n.language)}
                selected={value}
                mode="select"
                divided={false}
                onSelect={(code) => {
                  onChange(code);
                  setOpen(false);
                }}
              />
            </div>
          </>,
          document.body
        )
      : null;

  return (
    <div ref={triggerRef}>
      <Button
        variant="secondary"
        leftIcon={<Languages />}
        rightIcon={
          <ChevronDown
            className={`transition-transform duration-150 ${open ? 'rotate-180' : ''}`}
          />
        }
        aria-haspopup="menu"
        aria-expanded={open}
        aria-label={`${label}: ${valueLabel}`}
        disabled={disabled}
        onClick={() => setOpen((v) => !v)}
      >
        {valueLabel}
      </Button>
      {popover}
    </div>
  );
};

DocumentLanguagePicker.displayName = 'DocumentLanguagePicker';
