package com.buurman.domain;

import java.time.Instant;
import java.time.LocalDate;
import java.util.Optional;
import java.util.UUID;

import com.buurman.util.MoneyAmount;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@SuppressWarnings("NullAway.Init")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Payment {

  public enum PaymentStatus {
    PENDING,
    PARTIALLY_PAID,
    PAID,
    OVERDUE,
    LATE,
    CANCELLED
  }

  private UUID id;
  @Builder.Default private Optional<Sid> identifier = Optional.empty();
  private UUID teamId;
  private UUID contractId;
  private MoneyAmount amount;
  @Builder.Default private Optional<LocalDate> paymentDate = Optional.empty();
  private LocalDate dueDate;
  private PaymentStatus status;
  @Builder.Default private Optional<String> notes = Optional.empty();
  @Builder.Default private Boolean autoGenerated = false;
  private Instant createdAt;
  private Instant updatedAt;
  private UUID createdBy;
  private UUID updatedBy;
  @Builder.Default private Optional<Instant> deletedAt = Optional.empty();
}
