package com.buurman.mapper;

import static org.assertj.core.api.Assertions.assertThat;

import java.lang.reflect.Field;
import java.math.BigDecimal;
import java.util.Optional;
import java.util.UUID;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import com.buurman.domain.Unit;
import com.buurman.domain.UnitStatus;
import com.buurman.domain.UnitType;
import com.buurman.dto.request.UpdateUnitRequest;

/**
 * {@code allocationShare} and {@code wozSharePct} have exactly one writer: {@code PUT
 * /properties/{id}/allocation}. {@link UpdateUnitRequest} deliberately carries neither field
 * (BUUR-106 Important 7) so that {@link UnitMapper#updateEntity} — generated by MapStruct purely
 * from that record's fields — cannot null them out as a side effect of an unrelated edit. This test
 * guards the generated mapper, not just the DTO: a field re-added to {@link UpdateUnitRequest} with
 * the same name as a {@link Unit} field would silently restore the bug.
 */
@DisplayName("UnitMapper.updateEntity leaves allocationShare/wozSharePct untouched")
class UnitMapperTest {

  @Test
  @DisplayName(
      "an unrelated field update (e.g. energy label) does not clear the unit's existing"
          + " allocationShare or wozSharePct")
  void updateEntityDoesNotTouchAllocationOrWozShare() {
    UnitMapper mapper = wireRealUnitMapper();

    Unit unit =
        Unit.builder()
            .id(UUID.randomUUID())
            .teamId(UUID.randomUUID())
            .propertyId(UUID.randomUUID())
            .unitNumber("1")
            .unitType(UnitType.APARTMENT)
            .status(UnitStatus.OCCUPIED)
            .allocationShare(Optional.of(new BigDecimal("40")))
            .wozSharePct(Optional.of(new BigDecimal("35")))
            .build();

    UpdateUnitRequest request =
        new UpdateUnitRequest(
            "1",
            Optional.empty(),
            Optional.empty(),
            UnitType.APARTMENT,
            Optional.empty(),
            Optional.empty(),
            Optional.empty(),
            Optional.empty(),
            Optional.empty(),
            Optional.of("A"),
            Optional.empty(),
            Optional.empty(),
            Optional.empty(),
            Optional.empty(),
            Optional.empty(),
            Optional.empty(),
            Optional.empty(),
            Optional.empty(),
            Optional.empty(),
            Optional.empty(),
            Optional.empty(),
            Optional.empty());

    mapper.updateEntity(unit, request);

    assertThat(unit.getEnergyEfficiencyRating()).contains("A");
    assertThat(unit.getAllocationShare()).contains(new BigDecimal("40"));
    assertThat(unit.getWozSharePct()).contains(new BigDecimal("35"));
  }

  private static UnitMapper wireRealUnitMapper() {
    UnitMapperImpl impl = new UnitMapperImpl();
    try {
      Field field = UnitMapperImpl.class.getDeclaredField("optionalMappingConfig");
      field.setAccessible(true);
      field.set(impl, new OptionalMappingConfig());
    } catch (ReflectiveOperationException e) {
      throw new RuntimeException("Failed to wire OptionalMappingConfig into UnitMapperImpl", e);
    }
    return impl;
  }
}
