import { useState, useRef, useCallback } from 'react';
import { Link } from 'react-router-dom';
import { ModalWrapper } from '@buurman/ui';
import {
  Upload,
  ArrowRight,
  ArrowLeft,
  Check,
  AlertTriangle,
  FileSpreadsheet,
  X,
  History,
} from 'lucide-react';
import {
  useUploadImportFile,
  usePreviewImport,
  useExecuteImport,
} from '@/hooks/useImportHooks';
import { useFeatureFlags } from '@/context/FeatureFlagContext';
import { FeatureFlags } from '@/constants/featureFlags';
import {
  ContactTag,
  CONTACT_TYPE_LABELS,
  CONTACT_TAG_LABELS,
} from '@/types/contact';
import { trackEvent } from '@/utils/analytics';
import { AnalyticsEvent } from '@/constants/analyticsEvents';
import type {
  ImportUploadResponse,
  ImportPreviewResponse,
  ImportExecuteResponse,
  ImportPreviewRequestContactType,
  ImportExecuteRequestContactType,
  ImportPreviewRequestTagsItem,
  ImportExecuteRequestTagsItem,
} from '@/generated/models';
import { useTranslation } from 'react-i18next';

const CONTACT_FIELDS = [
  { value: '', label: '-- Skip this column --' },
  { value: 'firstName', label: 'First Name' },
  { value: 'lastName', label: 'Last Name' },
  { value: 'companyName', label: 'Company Name' },
  { value: 'tradeName', label: 'Trade Name' },
  { value: 'industry', label: 'Industry' },
  { value: 'email', label: 'Email' },
  { value: 'invoiceEmail', label: 'Invoice Email' },
  { value: 'phone', label: 'Phone (E.164)' },
  { value: 'website', label: 'Website' },
  { value: 'taxNumber', label: 'Tax Number' },
  { value: 'idNumber', label: 'ID Number' },
  { value: 'dateOfBirth', label: 'Date of Birth' },
  { value: 'idExpiryDate', label: 'ID Expiry Date' },
  { value: 'notes', label: 'Notes' },
] as const;

const CONTACT_TYPES: {
  value: ImportPreviewRequestContactType;
  label: string;
}[] = [
  { value: 'INDIVIDUAL', label: CONTACT_TYPE_LABELS.INDIVIDUAL },
  { value: 'COMPANY', label: CONTACT_TYPE_LABELS.COMPANY },
  { value: 'SERVICE_PROVIDER', label: CONTACT_TYPE_LABELS.SERVICE_PROVIDER },
];

const STATUS_BADGE_CLASSES: Record<string, string> = {
  CREATE:
    'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-300 px-2 py-0.5 rounded-full text-xs font-medium',
  SKIP: 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-300 px-2 py-0.5 rounded-full text-xs font-medium',
  ERROR:
    'bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-300 px-2 py-0.5 rounded-full text-xs font-medium',
};

// Columns that are auto-generated by Buurman and should never be imported
const IGNORED_COLUMNS = new Set([
  'identifier',
  'id',
  'sid',
  'uuid',
  'internal_id',
  'created_at',
  'updated_at',
  'deleted_at',
  'created_by',
  'updated_by',
  'createdat',
  'updatedat',
  'deletedat',
  'createdby',
  'updatedby',
]);

function isIgnoredColumn(col: string): boolean {
  return IGNORED_COLUMNS.has(col.toLowerCase().trim());
}

function guessMapping(columns: string[]): Record<string, string> {
  const mapping: Record<string, string> = {};
  const guessMap: Record<string, string[]> = {
    firstName: [
      'first name',
      'first_name',
      'firstname',
      'given name',
      'voornaam',
    ],
    lastName: [
      'last name',
      'last_name',
      'lastname',
      'surname',
      'family name',
      'achternaam',
    ],
    companyName: [
      'company',
      'company name',
      'company_name',
      'companyname',
      'bedrijf',
      'bedrijfsnaam',
    ],
    tradeName: ['trade name', 'trade_name', 'tradename', 'handelsnaam'],
    industry: ['industry', 'sector', 'branche'],
    email: ['email', 'e-mail', 'email address', 'emailaddress'],
    invoiceEmail: [
      'invoice email',
      'invoice_email',
      'invoiceemail',
      'billing email',
    ],
    phone: [
      'phone',
      'phone number',
      'phonenumber',
      'telephone',
      'tel',
      'mobile',
      'telefoon',
    ],
    website: ['website', 'url', 'web'],
    taxNumber: [
      'tax number',
      'tax_number',
      'taxnumber',
      'vat',
      'btw',
      'btw nummer',
    ],
    idNumber: ['id number', 'id_number', 'idnumber', 'bsn', 'identification'],
    dateOfBirth: [
      'date of birth',
      'date_of_birth',
      'dateofbirth',
      'dob',
      'birthday',
      'geboortedatum',
    ],
    idExpiryDate: [
      'id expiry',
      'id_expiry_date',
      'idexpirydate',
      'id expiry date',
    ],
    notes: ['notes', 'note', 'comment', 'comments', 'opmerkingen'],
  };

  for (const col of columns) {
    if (isIgnoredColumn(col)) {
      continue;
    }
    const normalized = col.toLowerCase().trim();
    for (const [field, aliases] of Object.entries(guessMap)) {
      if (aliases.includes(normalized)) {
        // Only assign if not already mapped
        const alreadyMapped = Object.values(mapping).includes(field);
        if (!alreadyMapped) {
          mapping[col] = field;
        }
        break;
      }
    }
  }
  return mapping;
}

interface ImportWizardProps {
  open: boolean;
  onClose: () => void;
}

export const ImportWizard = ({ open, onClose }: ImportWizardProps) => {
  const { t } = useTranslation('tenants');
  const { isEnabled } = useFeatureFlags();
  const [step, setStep] = useState(0);
  const [uploadResponse, setUploadResponse] =
    useState<ImportUploadResponse | null>(null);
  const [mappings, setMappings] = useState<Record<string, string>>({});
  const [contactType, setContactType] =
    useState<ImportPreviewRequestContactType>('INDIVIDUAL');
  const [selectedTags, setSelectedTags] = useState<
    ImportPreviewRequestTagsItem[]
  >([]);
  const [previewResponse, setPreviewResponse] =
    useState<ImportPreviewResponse | null>(null);
  const [executeResponse, setExecuteResponse] =
    useState<ImportExecuteResponse | null>(null);
  const [skipErrors, setSkipErrors] = useState(true);
  const [isDragging, setIsDragging] = useState(false);
  const [headerRow, setHeaderRow] = useState(true);
  const [lastFile, setLastFile] = useState<File | null>(null);

  const fileInputRef = useRef<HTMLInputElement>(null);
  const uploadMutation = useUploadImportFile();
  const previewMutation = usePreviewImport();
  const executeMutation = useExecuteImport();

  const acceptedFormats = isEnabled(FeatureFlags.EXCEL_EXPORT)
    ? '.csv,.xlsx'
    : '.csv';

  const reset = useCallback(() => {
    setStep(0);
    setUploadResponse(null);
    setMappings({});
    setContactType('INDIVIDUAL');
    setSelectedTags([]);
    setPreviewResponse(null);
    setExecuteResponse(null);
    setSkipErrors(true);
    setIsDragging(false);
    setHeaderRow(true);
    setLastFile(null);
    uploadMutation.reset();
    previewMutation.reset();
    executeMutation.reset();
  }, [uploadMutation, previewMutation, executeMutation]);

  const handleClose = () => {
    reset();
    onClose();
  };

  const handleFile = async (file: File, hasHeaderRow = true) => {
    trackEvent(AnalyticsEvent.CONTACT_IMPORT_STARTED);
    setLastFile(file);
    const result = await uploadMutation.mutateAsync({
      file,
      headerRow: hasHeaderRow,
    });
    setUploadResponse(result);
    setMappings(guessMapping(result.columns));
    setStep(1);
  };

  const handleHeaderRowToggle = async (checked: boolean) => {
    setHeaderRow(checked);
    if (lastFile) {
      const result = await uploadMutation.mutateAsync({
        file: lastFile,
        headerRow: checked,
      });
      setUploadResponse(result);
      setMappings(guessMapping(result.columns));
    }
  };

  const handleFileDrop = useCallback(
    (e: React.DragEvent) => {
      e.preventDefault();
      setIsDragging(false);
      const file = e.dataTransfer.files[0];
      if (file) {
        handleFile(file);
      }
    },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    []
  );

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      handleFile(file);
    }
  };

  const handlePreview = async () => {
    if (!uploadResponse) {
      return;
    }
    const cleanMappings: Record<string, string> = {};
    for (const [col, field] of Object.entries(mappings)) {
      if (field) {
        cleanMappings[col] = field;
      }
    }
    const result = await previewMutation.mutateAsync({
      fileName: uploadResponse.fileName,
      mappings: cleanMappings,
      contactType,
      tags: selectedTags.length > 0 ? selectedTags : undefined,
    });
    setPreviewResponse(result);
    setStep(2);
  };

  const handleExecute = async () => {
    if (!uploadResponse) {
      return;
    }
    const cleanMappings: Record<string, string> = {};
    for (const [col, field] of Object.entries(mappings)) {
      if (field) {
        cleanMappings[col] = field;
      }
    }
    const result = await executeMutation.mutateAsync({
      fileName: uploadResponse.fileName,
      mappings: cleanMappings,
      contactType: contactType as ImportExecuteRequestContactType,
      tags:
        selectedTags.length > 0
          ? (selectedTags as ImportExecuteRequestTagsItem[])
          : undefined,
      skipErrors,
    });
    setExecuteResponse(result);
    trackEvent(AnalyticsEvent.CONTACT_IMPORT_COMPLETED);
    setStep(3);
  };

  const toggleTag = (tag: ImportPreviewRequestTagsItem) => {
    setSelectedTags((prev) =>
      prev.includes(tag) ? prev.filter((t) => t !== tag) : [...prev, tag]
    );
  };

  const hasMappings = Object.values(mappings).some((v) => v !== '');

  const stepTitles = [
    t('import.steps.upload'),
    t('import.steps.map'),
    t('import.steps.preview'),
    t('import.steps.complete'),
  ];

  return (
    <ModalWrapper
      open={open}
      onClose={handleClose}
      title={t('import.title')}
      subtitle={stepTitles[step]}
      size="xl"
    >
      {/* Step Indicator */}
      <div className="flex items-center gap-2 mb-6 px-1">
        {stepTitles.map((title, i) => (
          <div key={title} className="flex items-center gap-2">
            <div
              className={`flex items-center justify-center w-7 h-7 rounded-full text-xs font-medium transition-colors ${
                i < step
                  ? 'bg-primary-500 text-white'
                  : i === step
                    ? 'bg-primary-100 text-primary-700 dark:bg-primary-900 dark:text-primary-300 ring-2 ring-primary-500'
                    : 'bg-surface-inset text-text-muted'
              }`}
            >
              {i < step ? <Check className="h-3.5 w-3.5" /> : i + 1}
            </div>
            <span
              className={`text-sm hidden sm:inline ${
                i === step ? 'text-text-primary font-medium' : 'text-text-muted'
              }`}
            >
              {title}
            </span>
            {i < stepTitles.length - 1 && (
              <div className="w-8 h-px bg-border-default" />
            )}
          </div>
        ))}
      </div>

      {/* Step 0: Upload */}
      {step === 0 && (
        <div className="space-y-4">
          <div
            className={`border-2 border-dashed rounded-lg p-8 text-center transition-colors ${
              isDragging
                ? 'border-primary-500 bg-primary-50 dark:bg-primary-950'
                : 'border-border-strong hover:border-primary-400'
            }`}
            onDragOver={(e) => {
              e.preventDefault();
              setIsDragging(true);
            }}
            onDragLeave={() => setIsDragging(false)}
            onDrop={handleFileDrop}
          >
            <FileSpreadsheet className="h-12 w-12 mx-auto text-text-muted mb-3" />
            <p className="text-text-primary font-medium mb-1">
              {t('import.dropFile')}{' '}
              <button
                type="button"
                onClick={() => fileInputRef.current?.click()}
                className="text-primary-500 hover:text-primary-600 underline"
              >
                browse
              </button>
            </p>
            <p className="text-sm text-text-muted">
              {t('import.supportedFormats')}
            </p>
            <input
              ref={fileInputRef}
              type="file"
              accept={acceptedFormats}
              onChange={handleFileSelect}
              className="hidden"
            />
          </div>

          {uploadMutation.isPending && (
            <div className="flex items-center justify-center gap-2 text-sm text-text-secondary">
              <div className="h-4 w-4 border-2 border-primary-500 border-t-transparent rounded-full animate-spin" />
              {t('import.uploading')}
            </div>
          )}

          <div className="flex items-center justify-between pt-2">
            <Link
              to="/contacts/imports"
              onClick={handleClose}
              className="text-sm text-text-secondary hover:text-primary-500 flex items-center gap-1.5 transition-colors"
            >
              <History className="h-4 w-4" />
              View import history
            </Link>
            <button
              type="button"
              onClick={handleClose}
              className="border border-border-strong bg-surface-card text-text-secondary px-4 py-2 rounded hover:border-primary-500 transition-colors text-sm"
            >
              Cancel
            </button>
          </div>
        </div>
      )}

      {/* Step 1: Map Columns */}
      {step === 1 && uploadResponse && (
        <div className="space-y-5">
          {/* File info */}
          <div className="bg-surface-inset rounded-lg px-4 py-3 flex items-center justify-between text-sm">
            <div className="flex items-center gap-2">
              <FileSpreadsheet className="h-4 w-4 text-text-muted" />
              <span className="text-text-primary font-medium">
                {uploadResponse.fileName}
              </span>
              <span className="text-text-muted">
                ({uploadResponse.totalRows} rows, {uploadResponse.fileFormat})
              </span>
            </div>
            <button
              type="button"
              onClick={reset}
              className="text-text-muted hover:text-text-primary"
              title={t('import.removeFile')}
            >
              <X className="h-4 w-4" />
            </button>
          </div>

          {/* Header row toggle */}
          <label className="flex items-center gap-2 text-sm cursor-pointer">
            <input
              type="checkbox"
              checked={headerRow}
              onChange={(e) => handleHeaderRowToggle(e.target.checked)}
              className="rounded border-border-strong text-primary-600 focus:ring-primary-500"
              disabled={uploadMutation.isPending}
            />
            <span className="text-text-secondary">{t('import.headerRow')}</span>
            {uploadMutation.isPending && (
              <span className="text-xs text-text-muted">
                {t('import.reparsing')}
              </span>
            )}
          </label>

          {/* Contact type */}
          <div>
            <label className="text-sm font-medium text-text-secondary mb-2 block">
              Contact Type
            </label>
            <div className="flex gap-2">
              {CONTACT_TYPES.map((ct) => (
                <button
                  key={ct.value}
                  type="button"
                  onClick={() => setContactType(ct.value)}
                  className={`px-3 py-1.5 text-sm rounded-full border transition-colors ${
                    contactType === ct.value
                      ? 'border-primary-500 bg-primary-50 text-primary-600 dark:bg-primary-950 dark:text-primary-300'
                      : 'border-border-strong text-text-secondary hover:border-primary-400'
                  }`}
                >
                  {ct.label}
                </button>
              ))}
            </div>
          </div>

          {/* Tags */}
          <div>
            <label className="text-sm font-medium text-text-secondary mb-2 block">
              Tags (optional)
            </label>
            <div className="flex flex-wrap gap-2">
              {Object.values(ContactTag).map((tag) => (
                <button
                  key={tag}
                  type="button"
                  onClick={() => toggleTag(tag as ImportPreviewRequestTagsItem)}
                  className={`px-3 py-1.5 text-sm rounded-full border transition-colors ${
                    selectedTags.includes(tag as ImportPreviewRequestTagsItem)
                      ? 'border-primary-500 bg-primary-50 text-primary-600 dark:bg-primary-950 dark:text-primary-300'
                      : 'border-border-strong text-text-secondary hover:border-primary-400'
                  }`}
                >
                  {CONTACT_TAG_LABELS[tag]}
                </button>
              ))}
            </div>
          </div>

          {/* Column mapping */}
          <div>
            <label className="text-sm font-medium text-text-secondary mb-2 block">
              Column Mapping
            </label>
            <div className="bg-surface-card border border-border-default rounded-lg overflow-hidden">
              <div className="grid grid-cols-[1fr_auto_1fr] gap-0 text-xs font-medium text-text-muted uppercase tracking-wider px-4 py-2 bg-surface-inset border-b border-border-default">
                <span>{t('import.sourceColumn')}</span>
                <span className="px-4" />
                <span>{t('import.targetField')}</span>
              </div>
              <div className="divide-y divide-border-default max-h-64 overflow-y-auto">
                {uploadResponse.columns
                  .filter((col) => !isIgnoredColumn(col))
                  .map((col) => (
                    <div
                      key={col}
                      className="grid grid-cols-[1fr_auto_1fr] items-center gap-0 px-4 py-2.5"
                    >
                      <span
                        className="text-sm text-text-primary truncate"
                        title={col}
                      >
                        {col}
                      </span>
                      <ArrowRight className="h-4 w-4 text-text-muted mx-3" />
                      <select
                        value={mappings[col] ?? ''}
                        onChange={(e) =>
                          setMappings((prev) => ({
                            ...prev,
                            [col]: e.target.value,
                          }))
                        }
                        className="border border-border-strong rounded px-2 py-1.5 text-sm bg-surface-card text-text-primary focus:border-primary-500 focus:ring-1 focus:ring-primary-500 w-full"
                      >
                        {CONTACT_FIELDS.map((f) => (
                          <option key={f.value} value={f.value}>
                            {f.label}
                          </option>
                        ))}
                      </select>
                    </div>
                  ))}
              </div>
            </div>
          </div>

          {/* Preview rows */}
          {uploadResponse.previewRows.length > 0 && (
            <div>
              <label className="text-sm font-medium text-text-secondary mb-2 block">
                {t('import.previewRows', {
                  count: uploadResponse.previewRows.length,
                })}
              </label>
              <div className="border border-border-default rounded-lg overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="bg-surface-inset border-b border-border-default">
                      {uploadResponse.columns
                        .filter((col) => mappings[col])
                        .map((col) => (
                          <th
                            key={col}
                            className="px-3 py-2 text-left text-xs font-medium text-text-muted uppercase tracking-wider whitespace-nowrap"
                          >
                            {CONTACT_FIELDS.find(
                              (f) => f.value === mappings[col]
                            )?.label ?? col}
                          </th>
                        ))}
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-border-default">
                    {uploadResponse.previewRows.slice(0, 3).map((row, idx) => (
                      <tr key={idx}>
                        {uploadResponse.columns
                          .filter((col) => mappings[col])
                          .map((col) => (
                            <td
                              key={col}
                              className="px-3 py-2 text-text-primary whitespace-nowrap"
                            >
                              {row[col] ?? ''}
                            </td>
                          ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              {!hasMappings && (
                <p className="text-xs text-text-muted mt-1 italic">
                  {t('import.mapAtLeastOne')}
                </p>
              )}
            </div>
          )}

          {/* Actions */}
          <div className="flex justify-between pt-2">
            <button
              type="button"
              onClick={reset}
              className="border border-border-strong bg-surface-card text-text-secondary px-4 py-2 rounded hover:border-primary-500 transition-colors flex items-center gap-1.5 text-sm"
            >
              <ArrowLeft className="h-4 w-4" />
              Back
            </button>
            <button
              type="button"
              onClick={handlePreview}
              disabled={!hasMappings || previewMutation.isPending}
              className="bg-primary-500 text-white px-4 py-2 rounded hover:bg-primary-600 transition-colors flex items-center gap-1.5 text-sm disabled:opacity-50"
            >
              {previewMutation.isPending ? (
                <>
                  <div className="h-4 w-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                  Previewing...
                </>
              ) : (
                <>
                  Preview
                  <ArrowRight className="h-4 w-4" />
                </>
              )}
            </button>
          </div>
        </div>
      )}

      {/* Step 2: Preview */}
      {step === 2 && previewResponse && (
        <div className="space-y-5">
          {/* Summary stats */}
          <div className="grid grid-cols-3 gap-3">
            <div className="bg-surface-card border border-border-default rounded-lg p-4 text-center">
              <p className="text-2xl font-bold text-green-600 dark:text-green-400">
                {previewResponse.toCreate}
              </p>
              <p className="text-xs text-text-muted mt-1">
                {t('import.toCreate')}
              </p>
            </div>
            <div className="bg-surface-card border border-border-default rounded-lg p-4 text-center">
              <p className="text-2xl font-bold text-yellow-600 dark:text-yellow-400">
                {previewResponse.toSkip}
              </p>
              <p className="text-xs text-text-muted mt-1">
                {t('import.toSkip')}
              </p>
            </div>
            <div className="bg-surface-card border border-border-default rounded-lg p-4 text-center">
              <p className="text-2xl font-bold text-red-600 dark:text-red-400">
                {previewResponse.errors}
              </p>
              <p className="text-xs text-text-muted mt-1">
                {t('import.errors')}
              </p>
            </div>
          </div>

          {/* Warning for errors */}
          {previewResponse.errors > 0 && (
            <div className="flex items-start gap-3 bg-yellow-50 dark:bg-yellow-950 border border-yellow-200 dark:border-yellow-800 rounded-lg p-3">
              <AlertTriangle className="h-5 w-5 text-yellow-600 dark:text-yellow-400 flex-shrink-0 mt-0.5" />
              <div>
                <p className="text-sm font-medium text-yellow-800 dark:text-yellow-200">
                  {t('import.rowsNotImported', {
                    count: previewResponse.errors,
                  })}
                </p>
                <p className="text-xs text-yellow-700 dark:text-yellow-300 mt-0.5">
                  {t('import.errorSkipNote')}
                </p>
                <label className="flex items-center gap-2 mt-2 text-sm text-yellow-800 dark:text-yellow-200">
                  <input
                    type="checkbox"
                    checked={skipErrors}
                    onChange={(e) => setSkipErrors(e.target.checked)}
                    className="rounded border-yellow-400"
                  />
                  {t('import.skipErrors')}
                </label>
              </div>
            </div>
          )}

          {/* Items table */}
          <div className="border border-border-default rounded-lg overflow-hidden">
            <div className="max-h-72 overflow-y-auto">
              <table className="w-full text-sm">
                <thead className="sticky top-0">
                  <tr className="bg-surface-inset border-b border-border-default">
                    <th className="px-3 py-2 text-left text-xs font-medium text-text-muted uppercase tracking-wider w-16">
                      Row
                    </th>
                    <th className="px-3 py-2 text-left text-xs font-medium text-text-muted uppercase tracking-wider w-20">
                      Status
                    </th>
                    <th className="px-3 py-2 text-left text-xs font-medium text-text-muted uppercase tracking-wider">
                      Name
                    </th>
                    <th className="px-3 py-2 text-left text-xs font-medium text-text-muted uppercase tracking-wider">
                      Email
                    </th>
                    <th className="px-3 py-2 text-left text-xs font-medium text-text-muted uppercase tracking-wider">
                      Details
                    </th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-border-default">
                  {previewResponse.items.map((item) => (
                    <tr key={item.rowNumber} className="hover:bg-surface-inset">
                      <td className="px-3 py-2 text-text-muted">
                        {item.rowNumber}
                      </td>
                      <td className="px-3 py-2">
                        <span className={STATUS_BADGE_CLASSES[item.status]}>
                          {item.status}
                        </span>
                      </td>
                      <td className="px-3 py-2 text-text-primary">
                        {item.displayName}
                      </td>
                      <td className="px-3 py-2 text-text-secondary">
                        {item.email ?? '-'}
                      </td>
                      <td className="px-3 py-2 text-text-secondary text-xs">
                        {item.status === 'ERROR' && item.errorMessage && (
                          <span className="text-red-600 dark:text-red-400">
                            {item.errorMessage}
                          </span>
                        )}
                        {item.status === 'SKIP' &&
                          item.duplicateOfDisplayName && (
                            <span className="text-yellow-700 dark:text-yellow-300">
                              {t('import.duplicateOf', {
                                name: item.duplicateOfDisplayName,
                              })}
                            </span>
                          )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {previewResponse.totalRows > previewResponse.items.length && (
            <p className="text-xs text-text-muted text-center">
              {t('import.showingOfTotal', {
                shown: previewResponse.items.length,
                total: previewResponse.totalRows,
              })}
            </p>
          )}

          {/* Actions */}
          <div className="flex justify-between pt-2">
            <button
              type="button"
              onClick={() => {
                setPreviewResponse(null);
                setStep(1);
              }}
              className="border border-border-strong bg-surface-card text-text-secondary px-4 py-2 rounded hover:border-primary-500 transition-colors flex items-center gap-1.5 text-sm"
            >
              <ArrowLeft className="h-4 w-4" />
              Back
            </button>
            <button
              type="button"
              onClick={handleExecute}
              disabled={
                executeMutation.isPending ||
                (previewResponse.toCreate === 0 && !skipErrors)
              }
              className="bg-primary-500 text-white px-4 py-2 rounded hover:bg-primary-600 transition-colors flex items-center gap-1.5 text-sm disabled:opacity-50"
            >
              {executeMutation.isPending ? (
                <>
                  <div className="h-4 w-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                  Importing...
                </>
              ) : (
                <>
                  <Upload className="h-4 w-4" />
                  {t('import.importCount', { count: previewResponse.toCreate })}
                </>
              )}
            </button>
          </div>
        </div>
      )}

      {/* Step 3: Result */}
      {step === 3 && executeResponse && (
        <div className="space-y-5">
          <div className="text-center py-4">
            <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-green-100 dark:bg-green-900 mb-4">
              <Check className="h-8 w-8 text-green-600 dark:text-green-400" />
            </div>
            <h3 className="text-lg font-semibold text-text-primary">
              Import Complete
            </h3>
            <p className="text-sm text-text-secondary mt-1">
              {t('import.importCompleteDescription')}
            </p>
          </div>

          {/* Stats */}
          <div className="grid grid-cols-3 gap-3">
            <div className="bg-surface-card border border-border-default rounded-lg p-4 text-center">
              <p className="text-2xl font-bold text-green-600 dark:text-green-400">
                {executeResponse.importedCount}
              </p>
              <p className="text-xs text-text-muted mt-1">
                {t('import.imported')}
              </p>
            </div>
            <div className="bg-surface-card border border-border-default rounded-lg p-4 text-center">
              <p className="text-2xl font-bold text-yellow-600 dark:text-yellow-400">
                {executeResponse.skippedCount}
              </p>
              <p className="text-xs text-text-muted mt-1">
                {t('import.skipped')}
              </p>
            </div>
            <div className="bg-surface-card border border-border-default rounded-lg p-4 text-center">
              <p className="text-2xl font-bold text-red-600 dark:text-red-400">
                {executeResponse.errorCount}
              </p>
              <p className="text-xs text-text-muted mt-1">Errors</p>
            </div>
          </div>

          {/* Actions */}
          <div className="flex justify-between pt-2">
            <Link
              to="/contacts/imports"
              onClick={handleClose}
              className="border border-border-strong bg-surface-card text-text-secondary px-4 py-2 rounded hover:border-primary-500 transition-colors flex items-center gap-1.5 text-sm"
            >
              <History className="h-4 w-4" />
              View Import History
            </Link>
            <button
              type="button"
              onClick={handleClose}
              className="bg-primary-500 text-white px-4 py-2 rounded hover:bg-primary-600 transition-colors flex items-center gap-1.5 text-sm"
            >
              <Check className="h-4 w-4" />
              Done
            </button>
          </div>
        </div>
      )}
    </ModalWrapper>
  );
};
