-- Add column to track auto-generated payments
ALTER TABLE payments ADD COLUMN auto_generated BOOLEAN DEFAULT FALSE NOT NULL;

-- Add index for finding auto-generated payments
CREATE INDEX idx_payments_auto_generated ON payments(auto_generated)
WHERE auto_generated = TRUE AND deleted_at IS NULL;

-- Add unique constraint for duplicate prevention
ALTER TABLE payments ADD CONSTRAINT unique_contract_due_date
UNIQUE(contract_id, due_date);

-- Add comment for documentation
COMMENT ON COLUMN payments.auto_generated IS 'Indicates if payment was automatically generated by scheduler';
