export const AnalyticsEvent = {
  PROPERTY_CREATED: 'property_created',
  PROPERTY_VIEWED: 'property_viewed',
  PROPERTY_DELETED: 'property_deleted',
  CONTACT_CREATED: 'contact_created',
  CONTACT_VIEWED: 'contact_viewed',
  CONTACT_DELETED: 'contact_deleted',
  CONTACT_TYPE_CHANGED: 'contact_type_changed',
  CONTACT_NOTE_CREATED: 'contact_note_created',
  CONTACT_RELATIONSHIP_CREATED: 'contact_relationship_created',
  CONTACT_TAG_ADDED: 'contact_tag_added',
  CONTACT_TAG_REMOVED: 'contact_tag_removed',
  CONTACT_QUICK_ADD_USED: 'contact_quick_add_used',
  CONTACT_DUPLICATE_WARNING_SHOWN: 'contact_duplicate_warning_shown',
  CONTACT_DUPLICATE_WARNING_IGNORED: 'contact_duplicate_warning_ignored',
  CONTACT_DATA_ERASED: 'contact_data_erased',
  CONTACT_IMPORT_STARTED: 'contact_import_started',
  CONTACT_IMPORT_COMPLETED: 'contact_import_completed',
  CONTACT_IMPORT_REVERTED: 'contact_import_reverted',
  SERVICE_PROVIDER_TAB_VIEWED: 'service_provider_tab_viewed',
  CONTRACT_CREATED: 'contract_created',
  CONTRACT_VIEWED: 'contract_viewed',
  LEASE_UNAVAILABLE_VIEWED: 'lease_unavailable_viewed',
  CONTRACT_STATUS_CHANGED: 'contract_status_changed',
  PAYMENT_CREATED: 'payment_created',
  PAYMENT_MARKED_PAID: 'payment_marked_paid',
  PAYMENTS_GENERATED: 'payments_generated',
  PAYMENT_REMINDER_SENT: 'payment_reminder_sent',
  PAYMENTS_BULK_MARKED_PAID: 'payments_bulk_marked_paid',
  PAYMENTS_BULK_REMINDERS_SENT: 'payments_bulk_reminders_sent',
  PAYMENT_CANCELLED: 'payment_cancelled',
  PAYMENTS_BULK_CANCELLED: 'payments_bulk_cancelled',
  LATE_FEE_WAIVED: 'late_fee_waived',
  PAYMENT_WRITTEN_OFF: 'payment_written_off',
  CREDIT_APPLIED: 'credit_applied',
  CREDIT_NOTE_CREATED: 'credit_note_created',
  CREDIT_REFUNDED: 'credit_refunded',
  PAYMENT_PLAN_CREATED: 'payment_plan_created',
  PAYMENT_PLAN_CANCELLED: 'payment_plan_cancelled',
  DEPOSIT_UPDATED: 'deposit_updated',
  EXPENSE_CREATED: 'expense_created',
  DOCUMENT_UPLOADED: 'document_uploaded',
  SIGNATURE_LINKS_OPENED: 'signature_links_opened',
  SIGNATURE_LINK_COPIED: 'signature_link_copied',
  SIGNATURE_LINK_SHARED: 'signature_link_shared',
  PHOTO_UPLOADED: 'photo_uploaded',
  TEAM_MEMBER_INVITED: 'team_member_invited',
  TEAM_SWITCHED: 'team_switched',
  // PWA install funnel
  PWA_INSTALL_PROMPT_AVAILABLE: 'pwa_install_prompt_available',
  PWA_INSTALL_PROMPT_SHOWN: 'pwa_install_prompt_shown',
  PWA_INSTALL_ACCEPTED: 'pwa_install_accepted',
  PWA_INSTALL_DISMISSED: 'pwa_install_dismissed',
  PWA_INSTALLED: 'pwa_installed',
} as const;

export type AnalyticsEventName =
  (typeof AnalyticsEvent)[keyof typeof AnalyticsEvent];
