export const AnalyticsEvent = {
  PROPERTY_CREATED: 'property_created',
  PROPERTY_DELETED: 'property_deleted',
  TENANT_CREATED: 'tenant_created',
  TENANT_DELETED: 'tenant_deleted',
  CONTRACT_CREATED: 'contract_created',
  CONTRACT_STATUS_CHANGED: 'contract_status_changed',
  PAYMENT_CREATED: 'payment_created',
  PAYMENT_MARKED_PAID: 'payment_marked_paid',
  PAYMENTS_GENERATED: 'payments_generated',
  EXPENSE_CREATED: 'expense_created',
  DOCUMENT_UPLOADED: 'document_uploaded',
  PHOTO_UPLOADED: 'photo_uploaded',
  TEAM_MEMBER_INVITED: 'team_member_invited',
  TEAM_SWITCHED: 'team_switched',
  REPORT_EXPORTED: 'report_exported',
  SEARCH_PERFORMED: 'search_performed',
} as const;
