package com.buurman.mapper;

import static java.time.ZoneOffset.UTC;

import java.util.Optional;

import org.jspecify.annotations.Nullable;
import org.springframework.stereotype.Component;

import com.buurman.domain.Payment;
import com.buurman.jooq.generated.tables.records.PaymentsRecord;
import com.buurman.util.CurrencyUtils;

@Component
public class PaymentRecordMapper {

  public Optional<Payment> toDomain(@Nullable PaymentsRecord record) {
    if (record == null) {
      return Optional.empty();
    }

    Payment payment = new Payment();
    payment.setId(record.getId());
    payment.setIdentifier(record.getIdentifier());
    payment.setTeamId(record.getTeamId());
    payment.setContractId(record.getContractId());
    payment.setAmount(CurrencyUtils.toMajorUnits(record.getAmount(), record.getCurrency()));
    payment.setCurrency(record.getCurrency());
    payment.setPaymentDate(Optional.ofNullable(record.getPaymentDate()));
    payment.setDueDate(record.getDueDate());
    payment.setStatus(Payment.PaymentStatus.valueOf(record.getStatus()));
    payment.setNotes(Optional.ofNullable(record.getNotes()));
    payment.setAutoGenerated(record.getAutoGenerated());
    if (record.getCreatedAt() != null) {
      payment.setCreatedAt(record.getCreatedAt().toInstant(UTC));
    }
    if (record.getUpdatedAt() != null) {
      payment.setUpdatedAt(record.getUpdatedAt().toInstant(UTC));
    }
    payment.setCreatedBy(record.getCreatedBy());
    payment.setUpdatedBy(record.getUpdatedBy());
    payment.setDeletedAt(Optional.ofNullable(record.getDeletedAt()).map(dt -> dt.toInstant(UTC)));

    return Optional.of(payment);
  }
}
