package com.buurman.mapper;

import static java.time.ZoneOffset.UTC;

import org.jspecify.annotations.Nullable;
import org.springframework.stereotype.Component;

import com.buurman.domain.Payment;
import com.buurman.jooq.generated.tables.records.PaymentsRecord;
import com.buurman.util.CurrencyUtils;

@Component
public class PaymentRecordMapper {

  public @Nullable Payment toDomain(@Nullable PaymentsRecord record) {
    if (record == null) {
      return null;
    }

    Payment payment = new Payment();
    payment.setId(record.getId());
    payment.setIdentifier(record.getIdentifier());
    payment.setTeamId(record.getTeamId());
    payment.setContractId(record.getContractId());
    payment.setAmount(CurrencyUtils.toMajorUnits(record.getAmount(), record.getCurrency()));
    payment.setCurrency(record.getCurrency());
    payment.setPaymentDate(record.getPaymentDate());
    payment.setDueDate(record.getDueDate());
    payment.setStatus(Payment.PaymentStatus.valueOf(record.getStatus()));
    payment.setNotes(record.getNotes());
    payment.setAutoGenerated(record.getAutoGenerated());
    if (record.getCreatedAt() != null) {
      payment.setCreatedAt(record.getCreatedAt().toInstant(UTC));
    }
    if (record.getUpdatedAt() != null) {
      payment.setUpdatedAt(record.getUpdatedAt().toInstant(UTC));
    }
    payment.setCreatedBy(record.getCreatedBy());
    payment.setUpdatedBy(record.getUpdatedBy());
    payment.setDeletedAt(
        record.getDeletedAt() != null ? record.getDeletedAt().toInstant(UTC) : null);

    return payment;
  }
}
