package com.buurman.mapper;

import com.buurman.domain.Payment;
import com.buurman.dto.request.CreatePaymentRequest;
import com.buurman.dto.request.UpdatePaymentRequest;
import com.buurman.dto.response.PaymentResponse;
import com.buurman.dto.response.PaymentSummary;
import org.mapstruct.BeanMapping;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

@Mapper(componentModel = "spring")
public interface PaymentMapper {

    @Mapping(target = "id", ignore = true)
    @Mapping(target = "identifier", ignore = true)
    @Mapping(target = "teamId", ignore = true)
    @Mapping(target = "contractId", ignore = true)
    @Mapping(target = "paymentDate", ignore = true)
    @Mapping(target = "status", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "createdBy", ignore = true)
    @Mapping(target = "updatedBy", ignore = true)
    @Mapping(target = "deletedAt", ignore = true)
    @Mapping(target = "autoGenerated", ignore = true)
    Payment toEntity(CreatePaymentRequest request);

    @Mapping(target = "contract", ignore = true)
    @Mapping(target = "tenant", ignore = true)
    @Mapping(target = "property", ignore = true)
    @Mapping(target = "proofOfPayment", ignore = true)
    @Mapping(target = "receipt", ignore = true)
    @Mapping(target = "receivedAmount", ignore = true)
    @Mapping(target = "balance", ignore = true)
    @Mapping(target = "receivals", ignore = true)
    PaymentResponse toResponse(Payment payment);

    PaymentSummary toSummary(Payment payment);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "identifier", ignore = true)
    @Mapping(target = "teamId", ignore = true)
    @Mapping(target = "contractId", ignore = true)
    @Mapping(target = "status", ignore = true)
    @Mapping(target = "paymentDate", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "createdBy", ignore = true)
    @Mapping(target = "updatedBy", ignore = true)
    @Mapping(target = "deletedAt", ignore = true)
    @Mapping(target = "autoGenerated", ignore = true)
    void updateEntity(@MappingTarget Payment payment, UpdatePaymentRequest request);
}
