package com.buurman.mapper;

import org.mapstruct.BeanMapping;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

import com.buurman.domain.Payment;
import com.buurman.dto.request.CreatePaymentRequest;
import com.buurman.dto.request.UpdatePaymentRequest;
import com.buurman.dto.response.PaymentResponse;
import com.buurman.dto.response.PaymentSummary;

@Mapper(componentModel = "spring", uses = OptionalMappingConfig.class)
public interface PaymentMapper {

  @Mapping(target = "id", ignore = true)
  @Mapping(target = "identifier", ignore = true)
  @Mapping(target = "teamId", ignore = true)
  @Mapping(target = "contractId", ignore = true)
  @Mapping(target = "paymentDate", ignore = true)
  @Mapping(target = "status", ignore = true)
  @Mapping(target = "createdAt", ignore = true)
  @Mapping(target = "updatedAt", ignore = true)
  @Mapping(target = "createdBy", ignore = true)
  @Mapping(target = "updatedBy", ignore = true)
  @Mapping(target = "contactId", ignore = true)
  @Mapping(target = "deletedAt", ignore = true)
  @Mapping(target = "autoGenerated", ignore = true)
  @Mapping(
      target = "amount",
      expression = "java(com.buurman.util.MoneyAmount.of(request.amount(), request.currency()))")
  Payment toEntity(CreatePaymentRequest request);

  @Mapping(target = "contract", ignore = true)
  @Mapping(target = "contact", ignore = true)
  @Mapping(target = "property", ignore = true)
  @Mapping(target = "proofOfPayment", ignore = true)
  @Mapping(target = "receipt", ignore = true)
  @Mapping(target = "receivedAmount", ignore = true)
  @Mapping(target = "balance", ignore = true)
  @Mapping(target = "receivals", ignore = true)
  @Mapping(target = "amount", expression = "java(payment.getAmount().value())")
  @Mapping(target = "currency", expression = "java(payment.getAmount().currency())")
  PaymentResponse toResponse(Payment payment);

  @Mapping(target = "amount", expression = "java(payment.getAmount().value())")
  @Mapping(target = "currency", expression = "java(payment.getAmount().currency())")
  PaymentSummary toSummary(Payment payment);

  @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
  @Mapping(target = "id", ignore = true)
  @Mapping(target = "identifier", ignore = true)
  @Mapping(target = "teamId", ignore = true)
  @Mapping(target = "contractId", ignore = true)
  @Mapping(target = "status", ignore = true)
  @Mapping(target = "paymentDate", ignore = true)
  @Mapping(target = "createdAt", ignore = true)
  @Mapping(target = "updatedAt", ignore = true)
  @Mapping(target = "createdBy", ignore = true)
  @Mapping(target = "updatedBy", ignore = true)
  @Mapping(target = "contactId", ignore = true)
  @Mapping(target = "deletedAt", ignore = true)
  @Mapping(target = "autoGenerated", ignore = true)
  @Mapping(
      target = "amount",
      expression =
          "java(com.buurman.util.MoneyAmount.of(request.amount().orElse(payment.getAmount().value()),"
              + " request.currency().orElse(payment.getAmount().currency())))")
  void updateEntity(@MappingTarget Payment payment, UpdatePaymentRequest request);
}
