package com.buurman.domain;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class Payment {

  public enum PaymentStatus {
    PENDING,
    PARTIALLY_PAID,
    PAID,
    OVERDUE,
    CANCELLED
  }

  private UUID id;
  private String identifier;
  private UUID teamId;
  private UUID contractId;
  private BigDecimal amount;
  private String currency;
  private LocalDate paymentDate;
  private LocalDate dueDate;
  private PaymentStatus status;
  private String notes;
  private Boolean autoGenerated;
  private Instant createdAt;
  private Instant updatedAt;
  private UUID createdBy;
  private UUID updatedBy;
  private Instant deletedAt;
}
