import type { LucideIcon } from 'lucide-react';
import {
  Home,
  Store,
  Factory,
  Wheat,
  Layers,
  Building2,
  Building,
  Castle,
  DoorOpen,
  LayoutDashboard,
  Ellipsis,
  Briefcase,
  ShoppingBag,
  UtensilsCrossed,
  BedDouble,
  Monitor,
  Car,
  Utensils,
  Coffee,
  KeyRound,
  Wine,
  Sunrise,
  Warehouse,
  Wrench,
  Cog,
  Server,
  Snowflake,
  SquareParking,
  TreePine,
  Sprout,
  Cherry,
  Grape,
} from 'lucide-react';
import { PropertyCategory, PropertyType } from '@/types/property';

export const PROPERTY_CATEGORY_ICONS: Record<PropertyCategory, LucideIcon> = {
  [PropertyCategory.RESIDENTIAL]: Home,
  [PropertyCategory.COMMERCIAL]: Store,
  [PropertyCategory.INDUSTRIAL]: Factory,
  [PropertyCategory.AGRICULTURAL]: Wheat,
  [PropertyCategory.MIXED_USE]: Layers,
};

export const PROPERTY_TYPE_ICONS: Record<string, LucideIcon> = {
  // Residential
  [PropertyType.APARTMENT]: Building2,
  [PropertyType.HOUSE]: Home,
  [PropertyType.STUDIO]: LayoutDashboard,
  [PropertyType.ROOM]: DoorOpen,
  [PropertyType.VILLA]: Castle,
  [PropertyType.TOWNHOUSE]: Building,
  [PropertyType.OTHER_RESIDENTIAL]: Ellipsis,
  // Commercial
  [PropertyType.OFFICE]: Briefcase,
  [PropertyType.RETAIL]: ShoppingBag,
  [PropertyType.RESTAURANT]: UtensilsCrossed,
  [PropertyType.HOTEL]: BedDouble,
  [PropertyType.SHOWROOM]: Monitor,
  [PropertyType.AUTO_DEALERSHIP]: Car,
  [PropertyType.SNACKBAR]: Utensils,
  [PropertyType.CAFE]: Coffee,
  [PropertyType.MOTEL]: KeyRound,
  [PropertyType.BAR]: Wine,
  [PropertyType.BED_AND_BREAKFAST]: Sunrise,
  [PropertyType.OTHER_COMMERCIAL]: Ellipsis,
  // Industrial
  [PropertyType.WAREHOUSE]: Warehouse,
  [PropertyType.WORKSHOP]: Wrench,
  [PropertyType.FACTORY]: Cog,
  [PropertyType.DATA_CENTER]: Server,
  [PropertyType.COLD_STORAGE]: Snowflake,
  [PropertyType.GARAGE]: SquareParking,
  [PropertyType.OTHER_INDUSTRIAL]: Ellipsis,
  // Agricultural
  [PropertyType.FARMLAND]: Wheat,
  [PropertyType.RANCH]: TreePine,
  [PropertyType.GREENHOUSE]: Sprout,
  [PropertyType.ORCHARD]: Cherry,
  [PropertyType.VINEYARD]: Grape,
  [PropertyType.OTHER_AGRICULTURAL]: Ellipsis,
  // Mixed-Use / Legacy
  [PropertyType.MIXED_USE]: Layers,
  [PropertyType.COMMERCIAL]: Store,
};
