#!/usr/bin/env bash
# =============================================================================
# Setup Parallel Workspace
# =============================================================================
# Configures this directory as workspace N (1-9) for parallel Buurman development.
# Each workspace gets isolated Docker services on unique ports and hostnames.
#
# Usage: ./scripts/setup-workspace.sh <workspace-number>
#
# Hostnames:  w{N}-app.local.buurman.io, w{N}-api.local.buurman.io, etc.
# HTTPS port: 443 + N*1000 (e.g., 1443 for workspace 1)
# TLS cert:   Reuses *.local.buurman.io wildcard (covers all subdomains)
#
# After setup, start the workspace:
#   make dev          — infrastructure only (backend/frontend on host)
#   make backend      — run backend on host (port offset applied)
#   cd frontend && yarn dev  — run frontend on host (port offset applied)
# =============================================================================
set -euo pipefail

WS=${1:?Usage: setup-workspace.sh <workspace-number> (1-9)}

if ! [[ "$WS" =~ ^[1-9]$ ]]; then
  echo "ERROR: Workspace number must be 1-9"
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# --- Reserve workspace via lock file (~/.buurman/workspaces/w{N}.lock) ---
LOCK_DIR="$HOME/.buurman/workspaces"
mkdir -p "$LOCK_DIR"
LOCK_FILE="$LOCK_DIR/w${WS}.lock"

if [ -f "$LOCK_FILE" ]; then
  echo "ERROR: Workspace ${WS} is already reserved ($(cat "$LOCK_FILE"))"
  echo ""
  echo "Available workspaces:"
  for n in $(seq 1 9); do
    if [ ! -f "$LOCK_DIR/w${n}.lock" ]; then
      echo "  $n"
    fi
  done
  exit 1
fi

echo "$PROJECT_DIR" > "$LOCK_FILE"
echo "Reserved workspace ${WS} (lock: $LOCK_FILE)"

# --- Port Calculations ---
HTTPS_PORT=$((443 + WS * 1000))
HTTP_PORT=$((80 + WS * 1000))
PG_HOST_PORT=$((5432 + WS * 1000))
TRAEFIK_DASHBOARD_PORT=$((8082 + WS * 1000))
SMTP_HOST_PORT=$((1025 + WS))
FLAGSMITH_HOST_PORT=$((8000 + WS * 1000))
BACKEND_HOST_PORT=$((8081 + WS * 100))
BACKEND_MGMT_HOST_PORT=$((8083 + WS * 100))
LOCAL_APP_PORT=$((5173 + WS * 10))
LOCAL_BACKOFFICE_PORT=$((5174 + WS * 10))

# --- Hostname Components ---
HP="w${WS}-"
PORT_SUFFIX=":${HTTPS_PORT}"
PROJECT_NAME="buurman-w${WS}"

echo "=== Workspace ${WS} Setup ==="
echo ""
echo "  Project name:     ${PROJECT_NAME}"
echo "  HTTPS port:       ${HTTPS_PORT}"
echo "  PostgreSQL port:  ${PG_HOST_PORT}"
echo "  Backend port:     ${BACKEND_HOST_PORT}"
echo "  App port:         ${LOCAL_APP_PORT}"
echo "  Backoffice port:  ${LOCAL_BACKOFFICE_PORT}"
echo "  Mailpit SMTP:     ${SMTP_HOST_PORT}"
echo ""
echo "  Base URL:         https://${HP}<service>.local.buurman.io${PORT_SUFFIX}"
echo ""

# =============================================================================
# 1. Generate .env
# =============================================================================
echo "Generating .env..."

if [ -f "$PROJECT_DIR/.env" ]; then
  cp "$PROJECT_DIR/.env" "$PROJECT_DIR/.env.bak"
  echo "  Backed up existing .env to .env.bak"
fi

cp "$PROJECT_DIR/.env.example" "$PROJECT_DIR/.env"

cat >> "$PROJECT_DIR/.env" << EOF

# =============================================================================
# Workspace ${WS} Configuration (auto-generated by setup-workspace.sh)
# =============================================================================
COMPOSE_PROJECT_NAME=${PROJECT_NAME}
HOSTNAME_PREFIX=${HP}

# Host port mappings (offset for workspace isolation)
HTTP_PORT=${HTTP_PORT}
HTTPS_PORT=${HTTPS_PORT}
PG_HOST_PORT=${PG_HOST_PORT}
TRAEFIK_DASHBOARD_PORT=${TRAEFIK_DASHBOARD_PORT}
SMTP_HOST_PORT=${SMTP_HOST_PORT}
FLAGSMITH_HOST_PORT=${FLAGSMITH_HOST_PORT}
BACKEND_HOST_PORT=${BACKEND_HOST_PORT}
BACKEND_MGMT_HOST_PORT=${BACKEND_MGMT_HOST_PORT}
LOCAL_BACKEND_PORT=${BACKEND_HOST_PORT}
LOCAL_APP_PORT=${LOCAL_APP_PORT}
LOCAL_BACKOFFICE_PORT=${LOCAL_BACKOFFICE_PORT}

# Override browser-facing URLs with workspace hostname + port
APP_BASE_URL=https://${HP}app.local.buurman.io${PORT_SUFFIX}
API_BASE_URL=https://${HP}api.local.buurman.io${PORT_SUFFIX}
VITE_KEYCLOAK_URL=https://${HP}keycloak.local.buurman.io${PORT_SUFFIX}
VITE_BACKOFFICE_KEYCLOAK_URL=https://${HP}keycloak.local.buurman.io${PORT_SUFFIX}
CORS_ALLOWED_ORIGINS=http://localhost:${LOCAL_APP_PORT},https://${HP}app.local.buurman.io${PORT_SUFFIX}
CORS_BACKOFFICE_ALLOWED_ORIGINS=http://localhost:${LOCAL_BACKOFFICE_PORT},https://${HP}backoffice.local.buurman.io${PORT_SUFFIX}
BACKEND_METRICS_TARGET=host.docker.internal:${BACKEND_HOST_PORT}
EOF

echo "  .env generated"

# =============================================================================
# 2. Generate Traefik dynamic config for local dev (host-mode backend/frontend)
# =============================================================================
echo "Generating Traefik local-dev.yml..."

cat > "$PROJECT_DIR/docker/traefik/dynamic/local-dev.yml" << EOF
# Routes for local development — workspace ${WS}
# Auto-generated by setup-workspace.sh. Do not edit manually.
# Backend + app running on host machine with workspace port offsets.

http:
  routers:
    backend-local:
      rule: "Host(\`${HP}api.local.buurman.io\`)"
      entryPoints:
        - websecure
      tls: {}
      service: backend-local
      priority: 10

    app-calendar-local:
      rule: "Host(\`${HP}app.local.buurman.io\`) && PathPrefix(\`/calendar/\`)"
      entryPoints:
        - websecure
      tls: {}
      service: backend-local
      priority: 20

    posthog-ingest-app-local:
      rule: "Host(\`${HP}app.local.buurman.io\`) && PathPrefix(\`/ingest\`)"
      entryPoints:
        - websecure
      tls: {}
      middlewares:
        - posthog-strip-prefix
      service: posthog-cloud
      priority: 30

    posthog-ingest-backoffice-local:
      rule: "Host(\`${HP}backoffice.local.buurman.io\`) && PathPrefix(\`/ingest\`)"
      entryPoints:
        - websecure
      tls: {}
      middlewares:
        - posthog-strip-prefix
      service: posthog-cloud
      priority: 30

    app-local:
      rule: "Host(\`${HP}app.local.buurman.io\`)"
      entryPoints:
        - websecure
      tls: {}
      service: app-local
      priority: 10

    backoffice-local:
      rule: "Host(\`${HP}backoffice.local.buurman.io\`)"
      entryPoints:
        - websecure
      tls: {}
      service: backoffice-local
      priority: 10

  middlewares:
    posthog-strip-prefix:
      stripPrefix:
        prefixes:
          - "/ingest"

  services:
    backend-local:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:${BACKEND_HOST_PORT}"

    app-local:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:${LOCAL_APP_PORT}"

    backoffice-local:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:${LOCAL_BACKOFFICE_PORT}"

    posthog-cloud:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://eu.i.posthog.com"
EOF

echo "  local-dev.yml generated"

# =============================================================================
# 3. Patch Keycloak realm JSONs (add workspace redirect URIs)
# =============================================================================
echo "Patching Keycloak realm configs..."

# buurman realm — add workspace redirect URIs for buurman-web client
REALM_FILE="$PROJECT_DIR/keycloak/buurman-realm.json"
WS_APP_URL="https://${HP}app.local.buurman.io${PORT_SUFFIX}/*"

if ! grep -q "$WS_APP_URL" "$REALM_FILE" 2>/dev/null; then
  if command -v python3 &>/dev/null; then
    python3 -c "
import json, sys
with open('$REALM_FILE', 'r') as f:
    data = json.load(f)
for client in data.get('clients', []):
    if client.get('clientId') == 'buurman-web':
        uris = client.get('redirectUris', [])
        uris.append('$WS_APP_URL')
        uris.append('http://localhost:${LOCAL_APP_PORT}/*')
        client['redirectUris'] = list(dict.fromkeys(uris))  # dedupe
        origins = client.get('webOrigins', [])
        origins.append('https://${HP}app.local.buurman.io${PORT_SUFFIX}')
        origins.append('http://localhost:${LOCAL_APP_PORT}')
        client['webOrigins'] = list(dict.fromkeys(origins))
with open('$REALM_FILE', 'w') as f:
    json.dump(data, f, indent=2)
"
    echo "  Patched buurman-realm.json"
  else
    echo "  WARNING: python3 not found, skipping realm patch. Add redirect URIs manually."
  fi
fi

# buurman-backoffice realm — add workspace redirect URIs
BACKOFFICE_REALM_FILE="$PROJECT_DIR/keycloak/buurman-backoffice-realm.json"
WS_BACKOFFICE_URL="https://${HP}backoffice.local.buurman.io${PORT_SUFFIX}/*"

if ! grep -q "$WS_BACKOFFICE_URL" "$BACKOFFICE_REALM_FILE" 2>/dev/null; then
  if command -v python3 &>/dev/null; then
    python3 -c "
import json, sys
with open('$BACKOFFICE_REALM_FILE', 'r') as f:
    data = json.load(f)
for client in data.get('clients', []):
    if client.get('clientId') == 'buurman-backoffice-web':
        uris = client.get('redirectUris', [])
        uris.append('$WS_BACKOFFICE_URL')
        uris.append('http://localhost:${LOCAL_BACKOFFICE_PORT}/*')
        client['redirectUris'] = list(dict.fromkeys(uris))
        origins = client.get('webOrigins', [])
        origins.append('https://${HP}backoffice.local.buurman.io${PORT_SUFFIX}')
        origins.append('http://localhost:${LOCAL_BACKOFFICE_PORT}')
        client['webOrigins'] = list(dict.fromkeys(origins))
with open('$BACKOFFICE_REALM_FILE', 'w') as f:
    json.dump(data, f, indent=2)
"
    echo "  Patched buurman-backoffice-realm.json"
  else
    echo "  WARNING: python3 not found, skipping realm patch."
  fi
fi

# =============================================================================
# 4. Generate backend env file for host-mode development
# =============================================================================
echo "Generating .env.backend for host-mode development..."

cat > "$PROJECT_DIR/.env.backend" << EOF
# Backend environment overrides for workspace ${WS}
# Source this before running the backend on the host:
#   source .env.backend && cd backend && mvn spring-boot:run -pl app -am
#
# Or use: make backend (which sources this automatically)

export SERVER_PORT=${BACKEND_HOST_PORT}
export MANAGEMENT_SERVER_PORT=${BACKEND_MGMT_HOST_PORT}
export SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:${PG_HOST_PORT}/buurman
export SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI=https://${HP}keycloak.local.buurman.io${PORT_SUFFIX}/realms/buurman
export SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI=https://${HP}keycloak.local.buurman.io${PORT_SUFFIX}/realms/buurman/protocol/openid-connect/certs
export SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_BACKOFFICE_ISSUERURI=https://${HP}keycloak.local.buurman.io${PORT_SUFFIX}/realms/buurman-backoffice
export SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_BACKOFFICE_JWKSETURI=https://${HP}keycloak.local.buurman.io${PORT_SUFFIX}/realms/buurman-backoffice/protocol/openid-connect/certs
export KEYCLOAK_ADMIN_SERVERURL=https://${HP}keycloak.local.buurman.io${PORT_SUFFIX}
export AWS_S3_ENDPOINT=https://${HP}seaweedfs.local.buurman.io${PORT_SUFFIX}
export AWS_S3_PUBLICENDPOINT=https://${HP}seaweedfs.local.buurman.io${PORT_SUFFIX}
export FLAGSMITH_APIURL=https://${HP}flagsmith.local.buurman.io${PORT_SUFFIX}/api/v1/
export SPRING_MAIL_PORT=${SMTP_HOST_PORT}
export APP_PUBLICURL=https://${HP}app.local.buurman.io${PORT_SUFFIX}
export APP_API_BASEURL=https://${HP}api.local.buurman.io${PORT_SUFFIX}
export APP_CORS_ALLOWEDORIGINS=http://localhost:${LOCAL_APP_PORT},https://${HP}app.local.buurman.io${PORT_SUFFIX}
export APP_CORS_BACKOFFICEALLOWEDORIGINS=http://localhost:${LOCAL_BACKOFFICE_PORT},https://${HP}backoffice.local.buurman.io${PORT_SUFFIX}
EOF

echo "  .env.backend generated"

# =============================================================================
# 5. Ensure TLS certificates exist
# =============================================================================
CERT_FILE="$PROJECT_DIR/docker/traefik/certs/local.pem"
if [ ! -f "$CERT_FILE" ]; then
  echo ""
  echo "TLS certificates not found. Generating..."
  bash "$SCRIPT_DIR/setup-local-certs.sh"
fi

DNS_HOSTS="${HP}app.local.buurman.io ${HP}api.local.buurman.io ${HP}keycloak.local.buurman.io ${HP}seaweedfs.local.buurman.io ${HP}seaweedfs-ui.local.buurman.io ${HP}mailpit.local.buurman.io ${HP}flagsmith.local.buurman.io ${HP}traefik.local.buurman.io ${HP}prometheus.local.buurman.io ${HP}grafana.local.buurman.io"
UNRESOLVED_HOSTS=""
for h in $DNS_HOSTS; do
  if ! dscacheutil -q host -a name "$h" | grep -q 'ip_address'; then
    UNRESOLVED_HOSTS="${UNRESOLVED_HOSTS} ${h}"
  fi
done

# =============================================================================
# 6. Summary
# =============================================================================
echo ""
echo "=== Setup Complete ==="
echo ""
if [ -n "$UNRESOLVED_HOSTS" ]; then
  echo "DNS: Add these to /etc/hosts:"
  echo "  127.0.0.1${UNRESOLVED_HOSTS}"
  echo ""
fi
echo "Start infrastructure:"
echo "  make dev"
echo "Start backend (in another terminal):"
echo "  make backend"
echo "Start frontends app (in other terminals):"
echo "  make frontend-app"
echo "  make frontend-backoffice"
echo ""
echo "Base URLs:"
echo "  https://${HP}<application>.local.buurman.io${PORT_SUFFIX}"
echo ""
echo "NOTE: Keycloak realm changes only take effect on first start. If Keycloak was already initialized, run: make down-v && make dev"
