package com.buurman.service.export.tabular;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import org.springframework.stereotype.Component;

import com.buurman.domain.Contract;
import com.buurman.domain.Payment;
import com.buurman.domain.Property;
import com.buurman.repository.ContractRepository;
import com.buurman.repository.PaymentRepository;
import com.buurman.repository.PropertyRepository;

import lombok.RequiredArgsConstructor;

/** Single-sheet TabularExport for all team payments, joined to contract + property address. */
@Component
@RequiredArgsConstructor
public class PaymentTabularExportBuilder {

  private final PaymentRepository paymentRepository;
  private final ContractRepository contractRepository;
  private final PropertyRepository propertyRepository;

  public TabularExport build(UUID teamId) {
    List<Payment> payments = paymentRepository.findAllByTeamId(teamId);

    // Index contracts (id → contract) and properties (id → address) for quick joins.
    Map<UUID, Contract> contractsById = new HashMap<>();
    for (Contract c : contractRepository.findAllByTeamId(teamId)) {
      contractsById.put(c.getId(), c);
    }
    Map<UUID, String> propertyAddressById = new HashMap<>();
    for (Property p : propertyRepository.findAllByTeamId(teamId)) {
      propertyAddressById.put(p.getId(), p.getStreet() + ", " + p.getCity());
    }

    TabularExport export = new TabularExport("payments");
    TabularSheet sheet =
        export.addSheet(
            "Payments",
            List.of(
                TabularColumn.text("Identifier"),
                TabularColumn.text("Contract"),
                TabularColumn.text("Property"),
                TabularColumn.of("Due Date", TabularColumnFormat.DATE),
                TabularColumn.of("Payment Date", TabularColumnFormat.DATE),
                TabularColumn.text("Status"),
                TabularColumn.of("Amount", TabularColumnFormat.CURRENCY),
                TabularColumn.text("Currency"),
                TabularColumn.text("Auto Generated"),
                TabularColumn.text("Notes"),
                TabularColumn.text("Created At"),
                TabularColumn.text("Updated At")));

    for (Payment p : payments) {
      Contract contract = contractsById.get(p.getContractId());
      String contractIdentifier =
          contract == null ? "" : contract.getIdentifier().map(Object::toString).orElse("");
      String propertyAddress =
          contract == null ? "" : propertyAddressById.getOrDefault(contract.getPropertyId(), "");

      sheet.addRow(
          p.getIdentifier().map(Object::toString).orElse(""),
          contractIdentifier,
          propertyAddress,
          p.getDueDate() != null ? p.getDueDate().toString() : "",
          p.getPaymentDate().map(Object::toString).orElse(""),
          p.getStatus().name(),
          p.getAmount() != null ? p.getAmount().value() : "",
          p.getAmount() != null ? p.getAmount().currency() : "",
          Boolean.TRUE.equals(p.getAutoGenerated()) ? "Yes" : "No",
          p.getNotes().orElse(""),
          p.getCreatedAt() != null ? p.getCreatedAt().toString() : "",
          p.getUpdatedAt() != null ? p.getUpdatedAt().toString() : "");
    }
    return export;
  }
}
