package com.buurman.mapper;

import static org.assertj.core.api.Assertions.assertThat;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.util.Optional;
import java.util.UUID;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import com.buurman.domain.Payment;
import com.buurman.domain.Payment.PaymentStatus;
import com.buurman.domain.Sid;
import com.buurman.jooq.generated.tables.records.PaymentsRecord;

@DisplayName("PaymentRecordMapper")
class PaymentRecordMapperTest {

  private final PaymentRecordMapper mapper = new PaymentRecordMapper();

  private static final UUID ID = UUID.randomUUID();
  private static final UUID TEAM_ID = UUID.randomUUID();
  private static final UUID CONTRACT_ID = UUID.randomUUID();
  private static final UUID CREATED_BY = UUID.randomUUID();
  private static final UUID UPDATED_BY = UUID.randomUUID();
  private static final Sid IDENTIFIER = Sid.of("PAY01HQJK4B2X5M3N7P8Q9R0S1T2");
  private static final LocalDateTime NOW = LocalDateTime.of(2026, 3, 1, 12, 0, 0);

  @Nested
  @DisplayName("toDomain")
  class ToDomain {

    @Test
    @DisplayName("returns empty Optional for null record")
    void returnsEmptyForNull() {
      Optional<Payment> result = mapper.toDomain(null);

      assertThat(result).isEmpty();
    }

    @Test
    @DisplayName("maps all fields from a complete record")
    void mapsCompleteRecord() {
      PaymentsRecord record = createCompleteRecord();

      Optional<Payment> result = mapper.toDomain(record);

      assertThat(result).isPresent();
      Payment payment = result.get();
      assertThat(payment.getId()).isEqualTo(ID);
      assertThat(payment.getIdentifier()).contains(IDENTIFIER);
      assertThat(payment.getTeamId()).isEqualTo(TEAM_ID);
      assertThat(payment.getContractId()).isEqualTo(CONTRACT_ID);
      assertThat(payment.getAmount().value()).isEqualByComparingTo(new BigDecimal("1200.00"));
      assertThat(payment.getAmount().currency()).isEqualTo("EUR");
      assertThat(payment.getDueDate()).isEqualTo(LocalDate.of(2026, 4, 1));
      assertThat(payment.getPaymentDate()).contains(LocalDate.of(2026, 3, 28));
      assertThat(payment.getStatus()).isEqualTo(PaymentStatus.PAID);
      assertThat(payment.getNotes()).contains("Monthly rent");
      assertThat(payment.getAutoGenerated()).isTrue();
      assertThat(payment.getCreatedAt()).isEqualTo(NOW.toInstant(ZoneOffset.UTC));
      assertThat(payment.getUpdatedAt()).isEqualTo(NOW.toInstant(ZoneOffset.UTC));
      assertThat(payment.getCreatedBy()).isEqualTo(CREATED_BY);
      assertThat(payment.getUpdatedBy()).isEqualTo(UPDATED_BY);
      assertThat(payment.getDeletedAt()).isEmpty();
    }

    @Test
    @DisplayName("maps all PaymentStatus enum values correctly")
    void mapsAllPaymentStatusValues() {
      for (PaymentStatus status : PaymentStatus.values()) {
        PaymentsRecord record = createCompleteRecord();
        record.setStatus(status.name());

        Optional<Payment> result = mapper.toDomain(record);

        assertThat(result).isPresent();
        assertThat(result.get().getStatus()).isEqualTo(status);
      }
    }

    @Test
    @DisplayName("wraps nullable paymentDate as empty Optional when null")
    void wrapsNullPaymentDateAsEmpty() {
      PaymentsRecord record = createCompleteRecord();
      record.setPaymentDate(null);

      Optional<Payment> result = mapper.toDomain(record);

      assertThat(result).isPresent();
      assertThat(result.get().getPaymentDate()).isEmpty();
    }

    @Test
    @DisplayName("wraps nullable notes as empty Optional when null")
    void wrapsNullNotesAsEmpty() {
      PaymentsRecord record = createCompleteRecord();
      record.setNotes(null);

      Optional<Payment> result = mapper.toDomain(record);

      assertThat(result).isPresent();
      assertThat(result.get().getNotes()).isEmpty();
    }

    @Test
    @DisplayName("maps deletedAt when present")
    void mapsDeletedAt() {
      PaymentsRecord record = createCompleteRecord();
      LocalDateTime deletedAt = LocalDateTime.of(2026, 6, 15, 10, 30, 0);
      record.setDeletedAt(deletedAt);

      Optional<Payment> result = mapper.toDomain(record);

      assertThat(result).isPresent();
      assertThat(result.get().getDeletedAt()).contains(deletedAt.toInstant(ZoneOffset.UTC));
    }

    @Test
    @DisplayName("maps MoneyAmount correctly with different currencies")
    void mapsMoneyAmountWithDifferentCurrencies() {
      PaymentsRecord record = createCompleteRecord();
      record.setAmount(new BigDecimal("2500.50"));
      record.setCurrency("USD");

      Optional<Payment> result = mapper.toDomain(record);

      assertThat(result).isPresent();
      assertThat(result.get().getAmount().value()).isEqualByComparingTo(new BigDecimal("2500.50"));
      assertThat(result.get().getAmount().currency()).isEqualTo("USD");
    }

    @Test
    @DisplayName("maps autoGenerated false correctly")
    void mapsAutoGeneratedFalse() {
      PaymentsRecord record = createCompleteRecord();
      record.setAutoGenerated(false);

      Optional<Payment> result = mapper.toDomain(record);

      assertThat(result).isPresent();
      assertThat(result.get().getAutoGenerated()).isFalse();
    }

    @Test
    @DisplayName("null amount creates MoneyAmount with null value (record accepts nulls)")
    @SuppressWarnings("NullAway")
    void nullAmountCreatesMoneyAmountWithNullValue() {
      PaymentsRecord record = createCompleteRecord();
      record.setAmount(null);

      // MoneyAmount is a Java record — its canonical constructor accepts nulls.
      // The mapper does not guard against this, so the resulting MoneyAmount has a null value.
      Optional<Payment> result = mapper.toDomain(record);

      assertThat(result).isPresent();
      assertThat(result.get().getAmount().value()).isNull();
    }

    @Test
    @DisplayName("null currency creates MoneyAmount with null currency (record accepts nulls)")
    @SuppressWarnings("NullAway")
    void nullCurrencyCreatesMoneyAmountWithNullCurrency() {
      PaymentsRecord record = createCompleteRecord();
      record.setCurrency(null);

      // MoneyAmount is a Java record — its canonical constructor accepts nulls.
      // The mapper does not guard against this, so the resulting MoneyAmount has a null currency.
      Optional<Payment> result = mapper.toDomain(record);

      assertThat(result).isPresent();
      assertThat(result.get().getAmount().currency()).isNull();
    }
  }

  private PaymentsRecord createCompleteRecord() {
    PaymentsRecord record = new PaymentsRecord();
    record.setId(ID);
    record.setIdentifier(IDENTIFIER);
    record.setTeamId(TEAM_ID);
    record.setContractId(CONTRACT_ID);
    record.setAmount(new BigDecimal("1200.00"));
    record.setCurrency("EUR");
    record.setDueDate(LocalDate.of(2026, 4, 1));
    record.setPaymentDate(LocalDate.of(2026, 3, 28));
    record.setStatus("PAID");
    record.setNotes("Monthly rent");
    record.setAutoGenerated(true);
    record.setCreatedAt(NOW);
    record.setUpdatedAt(NOW);
    record.setCreatedBy(CREATED_BY);
    record.setUpdatedBy(UPDATED_BY);
    record.setDeletedAt(null);
    return record;
  }
}
