package com.buurman.service.export;

import static java.util.stream.Collectors.joining;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Arrays;

/**
 * Shared HTML building utilities for all booklet/report exporters. All methods are static and
 * stateless — this is a pure utility class.
 */
final class BookletHelper {

  private BookletHelper() {}

  // ── Formatting ──────────────────────────────────────────────────

  static String escapeHtml(String text) {
    if (text == null) return "";
    return text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("\"", "&quot;")
        .replace("'", "&#39;");
  }

  static String sanitizeRichText(String html) {
    if (html == null) return "";
    return html.replaceAll("(?i)<script[^>]*>.*?</script>", "")
        .replaceAll("(?i)<iframe[^>]*>.*?</iframe>", "")
        .replaceAll("(?i)<object[^>]*>.*?</object>", "")
        .replaceAll("(?i)<embed[^>]*>", "")
        .replaceAll("(?i)<link[^>]*>", "")
        .replaceAll("(?i)\\s+on\\w+\\s*=\\s*\"[^\"]*\"", "")
        .replaceAll("(?i)\\s+on\\w+\\s*=\\s*'[^']*'", "");
  }

  static String formatEnumValue(String value) {
    if (value == null) return "";
    return Arrays.stream(value.split("_"))
        .map(word -> word.substring(0, 1).toUpperCase() + word.substring(1).toLowerCase())
        .collect(joining(" "));
  }

  static String fmt(BigDecimal value) {
    return value != null ? String.format("%,.2f", value) : "0.00";
  }

  static String formatDate(LocalDate date, DateTimeFormatter fmt) {
    return date != null ? date.format(fmt) : "—";
  }

  static boolean isTrue(Boolean value) {
    return Boolean.TRUE.equals(value);
  }

  // ── Document structure ──────────────────────────────────────────

  static void appendDocumentStart(StringBuilder html, String css) {
    html.append("<!DOCTYPE html><html><head><meta charset='UTF-8'/>");
    html.append("<style>");
    html.append(css);
    html.append("</style></head><body>");
  }

  static void appendDocumentEnd(StringBuilder html) {
    html.append("</body></html>");
  }

  // ── Running footer (shared by all booklets) ─────────────────────

  static void appendRunningFooter(StringBuilder html, String date) {
    html.append("<div class='running-footer'>");
    html.append("<table style='width:100%;border-collapse:collapse;'><tr>");
    html.append("<td style='text-align:left;font-size:9px;color:#a0aec0;width:33%;'>")
        .append(date)
        .append("</td>");
    html.append(
        "<td style='text-align:center;font-size:9px;color:#a0aec0;width:34%;'>Confidential &mdash;"
            + " Buurman Property Management</td>");
    html.append("<td style='text-align:right;font-size:9px;color:#a0aec0;width:33%;'></td>");
    html.append("</tr></table></div>");
  }

  // ── Cover page ──────────────────────────────────────────────────

  static void appendCoverStart(StringBuilder html, String title, String subtitle, String date) {
    html.append("<div class='cover'>");
    html.append("<div class='cover-header'>");
    html.append("<div class='cover-title'>").append(title).append("</div>");
    html.append("<div class='cover-subtitle'>").append(subtitle).append("</div>");
    html.append("<div class='cover-date'>Generated ").append(date).append("</div>");
    html.append("</div>");
  }

  static void appendStatusBadge(StringBuilder html, String status) {
    String statusStr = status != null ? status : "";
    html.append("<div style='text-align:center;margin:30px 0;'>");
    html.append("<span class='status-badge status-").append(statusStr.toLowerCase()).append("'>");
    html.append(formatEnumValue(statusStr));
    html.append("</span></div>");
  }

  static void appendCoverCell(StringBuilder html, String label, String value) {
    html.append("<td><div class='cs-label'>").append(escapeHtml(label)).append("</div>");
    html.append("<div class='cs-value'>").append(value).append("</div></td>");
  }

  static void appendCoverEnd(StringBuilder html) {
    html.append(
        "<div class='cover-footer'>Confidential &mdash; Generated by Buurman Property"
            + " Management</div>");
    html.append("</div>");
  }

  // ── Content pages ───────────────────────────────────────────────

  static void appendPageStart(StringBuilder html, String header) {
    html.append("<div class='page'>");
    html.append("<div class='page-header'>").append(header).append("</div>");
  }

  static void appendPageEnd(StringBuilder html) {
    html.append("</div>");
  }

  // ── Sections & fields ───────────────────────────────────────────

  static void appendSectionTitle(StringBuilder html, String title) {
    html.append("<h2 class='section-title'>").append(title).append("</h2>");
  }

  static void appendField(StringBuilder html, String label, String value) {
    html.append("<td><div class='fg-label'>").append(escapeHtml(label)).append("</div>");
    html.append("<div class='fg-value'>").append(value != null ? value : "—").append("</div></td>");
  }

  static void appendTextBlock(StringBuilder html, String label, String richTextContent) {
    if (richTextContent != null && !richTextContent.isBlank()) {
      html.append("<div class='text-block'><strong>")
          .append(escapeHtml(label))
          .append(":</strong> ")
          .append(sanitizeRichText(richTextContent))
          .append("</div>");
    }
  }

  // ── Summary cards ───────────────────────────────────────────────

  static void appendSummaryCard(
      StringBuilder html,
      String label,
      long count,
      String amount,
      String bgColor,
      String accentColor,
      String textColor) {
    appendSummaryCard(
        html,
        label,
        amount,
        count + (count == 1 ? " payment" : " payments"),
        bgColor,
        accentColor,
        textColor);
  }

  static void appendSummaryCard(
      StringBuilder html,
      String label,
      String amount,
      String subtitle,
      String bgColor,
      String accentColor,
      String textColor) {
    html.append("<td style='background-color:").append(bgColor).append(";'>");
    html.append("<div class='sc-label' style='color:")
        .append(accentColor)
        .append(";'>")
        .append(label)
        .append("</div>");
    html.append("<div class='sc-amount' style='color:")
        .append(textColor)
        .append(";'>")
        .append(amount)
        .append("</div>");
    if (subtitle != null && !subtitle.isBlank()) {
      html.append("<div class='sc-count' style='color:")
          .append(accentColor)
          .append(";'>")
          .append(subtitle)
          .append("</div>");
    }
    html.append("</td>");
  }

  // ── Check items (safety/accessibility) ──────────────────────────

  static void appendCheckItem(StringBuilder html, String label, Boolean value) {
    if (isTrue(value)) {
      html.append("<div class='check-item'><span class='check-icon'>&#10003;</span>")
          .append(escapeHtml(label))
          .append("</div>");
    }
  }
}
