package com.buurman.service.export;

import static com.buurman.service.export.BookletHelper.escapeHtml;

import java.math.BigDecimal;
import java.time.Clock;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.UUID;

import org.springframework.stereotype.Component;

import lombok.RequiredArgsConstructor;

@Component
@RequiredArgsConstructor
public class TransactionPdfExporter {

  private final TransactionDataLoader dataLoader;
  private final PdfRenderer pdfRenderer;
  private final Clock clock;

  public byte[] generate(LocalDate startDate, LocalDate endDate, UUID teamId) {
    List<TransactionRecord> transactions = dataLoader.load(startDate, endDate, teamId);

    BigDecimal totalIncome =
        transactions.stream()
            .filter(t -> "INCOME".equals(t.type()))
            .map(TransactionRecord::amount)
            .reduce(BigDecimal.ZERO, BigDecimal::add);

    BigDecimal totalExpenses =
        transactions.stream()
            .filter(t -> "EXPENSE".equals(t.type()))
            .map(TransactionRecord::amount)
            .reduce(BigDecimal.ZERO, BigDecimal::add);

    BigDecimal netTotal = totalIncome.subtract(totalExpenses);

    String html = buildHtml(transactions, startDate, endDate, totalIncome, totalExpenses, netTotal);
    return pdfRenderer.renderHtml(html);
  }

  private String buildHtml(
      List<TransactionRecord> transactions,
      LocalDate startDate,
      LocalDate endDate,
      BigDecimal totalIncome,
      BigDecimal totalExpenses,
      BigDecimal netTotal) {
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("MMM d, yyyy");
    String periodText =
        startDate != null && endDate != null
            ? startDate.format(formatter) + " to " + endDate.format(formatter)
            : "All Time";

    StringBuilder html = new StringBuilder();
    html.append("<!DOCTYPE html><html><head><meta charset='UTF-8'/>");
    html.append("<style>");
    appendCss(html);
    html.append("</style></head><body>");

    html.append("<h1>Transaction History Report</h1>");
    html.append("<p style='color: #6b7280; font-size: 14px;'>Period: ")
        .append(periodText)
        .append("</p>");
    html.append("<p style='color: #6b7280; font-size: 12px;'>Generated on: ")
        .append(LocalDate.now(clock).format(formatter))
        .append("</p>");

    // Summary cards
    html.append("<div class='summary'>");
    html.append("<div class='summary-card income'><h3>Total Income</h3><p>EUR ")
        .append(String.format("%.2f", totalIncome))
        .append("</p></div>");
    html.append("<div class='summary-card expense'><h3>Total Expenses</h3><p>EUR ")
        .append(String.format("%.2f", totalExpenses))
        .append("</p></div>");
    html.append("<div class='summary-card net'><h3>Net Total</h3><p>EUR ")
        .append(String.format("%.2f", netTotal))
        .append("</p></div>");
    html.append("</div>");

    // Transaction table
    html.append("<h2>Transactions (").append(transactions.size()).append(")</h2>");
    html.append("<table>");
    html.append("<thead><tr>");
    html.append(
        "<th>Date</th><th>Type</th><th>Description</th><th>Property</th><th>Category</th><th"
            + " style='text-align: right;'>Amount</th>");
    html.append("</tr></thead><tbody>");

    for (TransactionRecord t : transactions) {
      html.append("<tr>");
      html.append("<td>").append(t.date().format(formatter)).append("</td>");
      html.append("<td><span class='")
          .append(t.type().equals("INCOME") ? "income-badge" : "expense-badge")
          .append("'>")
          .append(t.type())
          .append("</span></td>");
      html.append("<td>").append(escapeHtml(t.description())).append("</td>");
      html.append("<td>").append(escapeHtml(t.property())).append("</td>");
      html.append("<td>")
          .append(t.category() != null ? escapeHtml(t.category()) : "-")
          .append("</td>");
      html.append("<td style='text-align: right;' class='")
          .append(t.type().equals("INCOME") ? "amount-income" : "amount-expense")
          .append("'>")
          .append(t.type().equals("INCOME") ? "+" : "-")
          .append(t.currency())
          .append(" ")
          .append(String.format("%.2f", t.amount()))
          .append("</td>");
      html.append("</tr>");
    }

    html.append("</tbody></table>");
    html.append("<div class='footer'>Generated by Buurman Property Management</div>");
    html.append("</body></html>");

    return html.toString();
  }

  private void appendCss(StringBuilder css) {
    css.append("body { font-family: Arial, sans-serif; margin: 40px; color: #333; }");
    css.append("h1 { color: #1e40af; border-bottom: 3px solid #3b82f6; padding-bottom: 10px; }");
    css.append("h2 { color: #1e40af; margin-top: 30px; }");
    css.append(".summary { display: flex; gap: 20px; margin: 20px 0; }");
    css.append(".summary-card { flex: 1; padding: 15px; border-radius: 8px; }");
    css.append(".income { background-color: #d1fae5; border: 2px solid #10b981; }");
    css.append(".expense { background-color: #fee2e2; border: 2px solid #ef4444; }");
    css.append(".net { background-color: #dbeafe; border: 2px solid #3b82f6; }");
    css.append(".summary-card h3 { margin: 0 0 5px 0; font-size: 14px; color: #666; }");
    css.append(".summary-card p { margin: 0; font-size: 24px; font-weight: bold; }");
    css.append("table { width: 100%; border-collapse: collapse; margin-top: 20px; }");
    css.append(
        "th { background-color: #f3f4f6; padding: 12px; text-align: left; font-weight: 600;"
            + " border-bottom: 2px solid #d1d5db; }");
    css.append("td { padding: 10px; border-bottom: 1px solid #e5e7eb; }");
    css.append("tr:hover { background-color: #f9fafb; }");
    css.append(
        ".income-badge { background-color: #d1fae5; color: #065f46; padding: 4px 8px;"
            + " border-radius: 4px; font-size: 12px; font-weight: 600; }");
    css.append(
        ".expense-badge { background-color: #fee2e2; color: #991b1b; padding: 4px 8px;"
            + " border-radius: 4px; font-size: 12px; font-weight: 600; }");
    css.append(".amount-income { color: #059669; font-weight: 600; }");
    css.append(".amount-expense { color: #dc2626; font-weight: 600; }");
    css.append(
        ".footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #d1d5db; text-align:"
            + " center; color: #6b7280; font-size: 12px; }");
  }
}
